### ISSUE TITLE
CCC Eng/Math Assessment page requires modifying to fit newly expanded information from CSUs and UCs.  

### ISSUE THREAD

**Issue by Ruth-DeTro** [woodwarddesign/ccc-transfer#189]
See my 12/1/14 email with content add so you can see how long this vital information is and how much space is required.

**Comment by Ruth-DeTro** [comment]
How is the expansion of text cell limitations coming along (E.g. to accommodate CSU and UC assessment data).  I have been receiving several requests for this information to be posted and was under the impression this would be completed within 5 to 10 working days.  Please provide a deadline date that I can relay to viewers.  Thanks!

**Comment by Ruth-DeTro** [comment]
Sorry - Michael - after entering above comment I accidentally closed and had to reopen this issue.  My bad...

**Comment by mlwoodward** [comment]
Made all fields have infinite text allow.  After doing this Ruth and I added actual text and found that it was very difficult to use.  This is due to the limitation of the actual space available.  Ruth recommended attaching PDFs for these fields.  I built in the ability to add links into these fields and Ruth has updated the content.  Looks like this solution will work!
