### ISSUE TITLE
Design: Statistics: In page menus

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#71]
joomla/source: http://ccctransfer.org/statistics

dev: http://dev-ccc-transfer.gotpantheon.com/statistics

The Statistics page has an in-page menu containing four sections – the in-page menu is included on the new site but is also scattered all over and not linked to anything.

**Comment by DirectorWho** [comment]
@wdg-thomas The only spacing i'm seeing here is caused by the use of a table. I'm presuming this critique is based on their looking at the site on desktop. 

A bigger concern for me is the fact that this menu breaks on mobile. It will not fit in the space provided. This is look is caused directly by the markup.

**Comment by DirectorWho** [comment]
This has been corrected. This will be further refined once the tables are made responsive.
